### ISSUE TITLE
Request to Change the 13th Line Power to Strength

### ISSUE THREAD

**Issue by AllwinGain** [HanushRegupathy/Test-Github#5]
Hi Hanush,

As I have added the feature for your code, in that Kindly note down the change of Line 13 whereas I have updated as "Power". Kindly change it back to "Strength"

**Comment by HanushRegupathy** [comment]
Sure, Allwin Thanks for the update.

**Comment by HanushRegupathy** [comment]
Hi Allwin,

Updated the changes as per your request reported in the Issue
